# Generated by Django 4.2.1 on 2023-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=60)),
                ('photos', models.ImageField(upload_to='')),
                ('featured', models.BooleanField()),
            ],
        ),
    ]
