# Generated by Django 4.2.1 on 2023-05-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbApi', '0004_alter_listing_id_proimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
