# Generated by Django 4.2.1 on 2023-05-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbApi', '0005_alter_listing_photos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProImage',
            new_name='ListingImages',
        ),
    ]
