# Generated by Django 4.2.1 on 2023-05-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbApi', '0006_rename_proimage_listingimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, default=True, null=True),
        ),
    ]
