# Generated by Django 4.2.1 on 2023-05-24 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbApi', '0007_listing_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingImages',
            new_name='ListingImage',
        ),
    ]
